config/routes.rb
DemoApp::Application.routes.draw do
  root :to => 'contacts#index'
  get 'welcome' => 'welcome#index', :as => 'welcome'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'help' => 'help#index', :as => 'help'
  get '/contacts/export' => 'contacts#export', :as => 'export_contacts'
  get '/contacts/treeview' => 'contacts#treeview', :as => 'contacts_treeview'
  get '/contacts/:id/edit_inline' => 'contacts#edit_inline', :as => 'edit_inline_contact'
  match '/contacts/update_views_for_technology/:tech' => 'contacts#update_views_for_technology', :as => 'contacts/update_views_for_technology'

  post '/contacts/update_lead_type' => 'contacts#update_lead_type', :as => 'contacts/update_lead_type'

  resources :contacts
  resources :sessions

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :first_name, :last_name, :email, :lead_type
  attr_accessor :govt_contract, :dod, :other

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/lead_type.rb
class LeadType < ActiveRecord::Base
  LEAD_TYPES = ['HOT', 'NEUTRAL', 'COLD']
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  TYPES = [ "HTML5", "RadControls" ]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :require_login
  helper_method :current_user

  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  # For all responses in this controller, return the CORS access control headers.

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  # If this is a preflight OPTIONS request, then short-circuit the
  # request, return only the necessary headers and return an empty
  # text/plain.

  def cors_preflight_check
    if request.method.intern == :OPTIONS
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'Content-Type, Accept'
      headers['Access-Control-Max-Age'] = '1728000'
      render :text => '', :content_type => 'text/plain'
    end
  end

  private

  def require_login
    unless current_user || request.format == 'json'
      redirect_to welcome_url
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/contacts_controller.rb
require 'prawn'
require 'json'

class ContactsController < ApplicationController

  skip_before_filter :require_login, :only => :update_views_for_technology

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  
  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # GET /contacts/1/edit_inline
  def edit_inline
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def delay_three_seconds_and_spike_cpu
	begin
		Timeout.timeout(3) do	
			$loopCount = 100
			$index = 0
			
			while $index < $loopCount do
				100000000000.times{ (1231231232312313 * 12312312312312312312) / 
									(12873612876312873621 * 123123123123) }
				$index+=1
			end
		end
	rescue 
	end
  end
  
  # POST /contacts
  # POST /contacts.json
  def create
  
	# Uncomment the following method call when you need to demo a short delay
	# and CPU spike when saving a new contact.
	
	#delay_three_seconds_and_spike_cpu
	

    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_url, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to contacts_url, notice: 'Contact was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :ok }
    end
  end

  def update_lead_type
    @contact = Contact.find(params[:id])
    @contact.lead_type = params[:lead_type]

    respond_to do |format|
      if @contact.save
        format.json { render json: @contact }
      else
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def export
    @contacts = Contact.all
    Prawn::Document.generate('contacts.pdf') do |pdf|
      @contacts.each do |contact|
        pdf.text contact.to_json
      end
    end
    send_file('contacts.pdf')
  end

  def treeview
    @contacts = Contact.all
  end

  def update_views_for_technology
    sleep 1
	
    @technology = params[:tech]

    @technology_views = {
      "HTML5" => [ "HTML5 Grid", "HTML5 Tree" ],
      "RadControls" => [ "RadGrid", "RadTree" ]
    }

    respond_to do |format|
      format.json { render json: @technology_views[@technology] }
    end
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login

  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash.now.notice = "Logged in!"
      respond_to do |format|
        format.js { render :redirect }
      end
    else
      flash.now.alert = "Invalid username or password"
      respond_to do |format|
        format.js # create.js.erb
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url
    else
      render "new"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :require_login

  def index
    redirect_to contacts_url if current_user
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
  def lead_type_icon(lead_type)
    lead_type_icons = { 'HOT' => 'HOT.png',
                        'COLD' => 'COLD.png',
                        'NEUTRAL' => 'NEUTRAL.png' }
    lead_type_icons[lead_type]
  end
end

app/views/contacts/_description.html.erb
<div id="description">
  <h2>Demonstration Application: Customer Relations Management System</h2>

  <p>This is a demonstration application designed to help you evaluate Telerik's Test Studio. The application is a skeleton around the metaphor of a Customer Relations Management (CRM) system. You can create new contacts, view existing ones, export the grid to a file, and a number of other actions.</p>
  <p>This CRM application is <strong>not</strong> a real application; it's designed to give you the chance to work with several common problems around automation. This way you'll be able to use Test Studio and see how well it works! You can use the existing Test Studio project under test/TestStudio, or you can create your own.</p>

</div>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, 'type' => 'email' %>
  </div>
  <div class="field">
    <%= f.label :linkedin_profile %><br />
    <%= f.text_field :linkedin_profile %> 
  </div>
  <div class="field">
    <%= f.check_box :govt_contract %>
    <%= f.label :govt_contract, "Gov't Contract?" %>
  </div>
  <div class="field" id="govt_contracts">
    <%= f.check_box :dod %>
    <%= f.label :dod, "DOD" %><br />
    <%= f.check_box :other %>
    <%= f.label :other, "Other" %>
  </div>
  <div id="lead_types">
    <%= image_tag 'HOT.png'     , 'draggable' => true , 'data-lead_type' => 'HOT' %>
    <%= image_tag 'NEUTRAL.png' , 'draggable' => true , 'data-lead_type' => 'NEUTRAL'%>
    <%= image_tag 'COLD.png'    , 'draggable' => true , 'data-lead_type' => 'COLD' %>
  </div>
  <div class="field">
	  
    <p>Drag a lead type to the box below</p>
    <div class="drop_target">
      <%= image_tag(lead_type_icon(@contact.lead_type)) if @contact.lead_type %>
    </div>
    <%= f.hidden_field :lead_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <%= button_to_function 'Cancel', 'window.close()' unless controller.action_name == 'edit_inline' %>
  </div>
<% end %>

app/views/contacts/_lead_type_dialog.html.erb
<div id='lead_type_dialog' title='Lead Type'>
  <div id='lead_types'>
    <%= image_tag 'HOT.png'     , :class => 'lead_type_selection' , 'data-lead_type' => 'HOT' %>
    <%= image_tag 'NEUTRAL.png' , :class => 'lead_type_selection' , 'data-lead_type' => 'NEUTRAL' %>
    <%= image_tag 'COLD.png'    , :class => 'lead_type_selection' , 'data-lead_type' => 'COLD'  %>
  </div>
</div>

app/views/contacts/_linkedin_frame.html.erb
<iframe id='linkedin_frame' width='100%' height='100%'>
  <p>Your browser does not support iframes.</p>
</iframe>

app/views/contacts/_moreInfo.html.erb
<div id="moreInfo">
	<p>Interested in learing more about Test Studio? Visit us at <a href="http://www.telerik.com/automated-testing-tools.aspx?utm_source=TS_CRM_Demo_App&utm_medium=TS_site&utm_campaign=TS_HP">the Test Studio home page.</a> You can also <a href="http://www.telerik.com/automated-testing-tools/download.aspx?utm_source=TS_CRM_Demo_App&utm_medium=TS_site&utm_campaign=TS_Download_Trial">download a fully functional trial of Test Studio</a> complete with our full priority support to help you get started!</p>
</div>

app/views/contacts/_selection.html.erb
<div id="selection">
  <%= select "selection", "technology", Technology::TYPES, :prompt => "Select Technology" %>
  <%= select_tag("selection_view", [], {:prompt => "Select View", :disabled => "disabled"}) %>
</div>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= render 'linkedin_frame' %>

app/views/contacts/edit_inline.js.erb
$('#inline_contact_edit_form').html("<%= escape_javascript(render('form')) %>");
attachDraggables();
attachDropTargets();
$('#govt_contracts').hide();

app/views/contacts/index.html.erb
<%= render 'description' %>

<p id="notice"><%= notice %></p>

<h2>
  HTML5 Grid
  <%= render 'selection' %>
</h2>

<table id="contacts">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>LinkedIn</th>
    <th>Lead Type</th>
    <th>Action</th>
  </tr>

<% @contacts.each do |contact| %>
  <tr class="<%= cycle('even', 'odd') %>">
    <td><%= contact.first_name %></td>
    <td><%= contact.last_name %></td>
    <td><%= contact.email %></td>
    <td><%= contact.linkedin_profile %></td>
    <td id="lead_type_cell-<%= contact.id %>"><%= image_tag lead_type_icon(contact.lead_type), :size => '23x23', :class => 'contact_lead_type', 'data-contact_id' => contact.id %></td>
    <td><%= link_to 'View Contact', edit_contact_path(contact), 'target' => '_blank' %></td>
  </tr>
<% end %>
<% (10 - @contacts.count).times do %>
  <tr class="<%= @contacts.count.even? ? cycle('even', 'odd') : cycle('odd', 'even') %>">
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<% end %>
</table>

<br />

<div id="buttons">
  <div class="left">
    <%= link_to 'New Contact', new_contact_path, 'target' => '_blank', :class => 'large_button gray' %>
  </div>

  <div class="right">
    <%= link_to 'Export to PDF', export_contacts_path, :class => 'large_button green' %>
  </div>
</div>

<%= render 'lead_type_dialog' %>

<%= render 'moreInfo' %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= render 'linkedin_frame' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @contact.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Linkedin profile:</b>
  <%= @contact.linkedin_profile %>
</p>

<p>
  <b>Lead type:</b>
  <%= image_tag lead_type_icon(@contact.lead_type), :size => '13x13' %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/treeview.html.erb
<h2>
  HTML5 Tree 
  <%= render 'selection' %>
</h2>

<div id="treeview">
  <ul>
    <% LeadType::LEAD_TYPES.each do |lead_type| %>
      <li><%= link_to lead_type, '#', :class => 'lead_type_parent', 'data-lead_type' => lead_type %></li>
      <ul class="lead_type_children <%= lead_type %>">
        <% @contacts.find_all { |c| c.lead_type == lead_type }.each do |contact_with_lead_type| %>
          <li><%= link_to contact_with_lead_type.full_name,
            edit_inline_contact_path(contact_with_lead_type),
            'data-contact_id' => contact_with_lead_type.id,
            :remote => true %></li>
        <% end %>
      </ul>
    <% end %>
  </ul>
</div>

<div id="inline_contact_edit_form">
</div>

app/views/help/index.html.erb
<div id="help-video">
  <video width="420"
         height="345"
         preload
         controls>
         <source src="assets/dublin.m4v">
         <!--source src="assets/dublin.mp4"-->
         <source src="assets/dublin.ogg">
         <source src="assets/dublin.webm">
         <!--source src="assets/movie.m4v"-->
         <source src="assets/movie.mov">
         <!--source src="assets/movie_web.m4v"-->
         <!--source src="assets/movie_web.mp4"-->
         Your browser does not support the video tag.
  </video>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Telerik Customer Relations Management System</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="top-bar">
    <h1><%= image_tag 'TelerikLogo.png' %> </h1>
    <div id="top-menu">
	    <%= link_to 'Home', root_path, :id => 'home_link' %>
	    <%#= link_to 'FAQs', root_path, :id => 'faq_link' %>
      <%= link_to 'Help', help_path, :id => 'help_link' %>
      <%= render 'sessions/login' %>
    </div>
  </div>


  <div id="body">
    <h2><%= image_tag 'TestStudioLogo.png' %> </h2>
    <div id="content">
      <%= yield %>
    </div>
  </div>

  <% if not current_user %>
    <%= render 'sessions/form' %>
  <% end %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<p>You must be logged in to access this application.</p>